UART thermostat: src/commands.c File Reference
commands.c File Reference
#include <avr/io.h>
#include "uart.h"
#include "commands.h"
#include <string.h>
#include "room_manager.h"
#include <stdlib.h>
Functions
void initCommands (void)
Used only to initialize the command structs function pointer to NULL.
void taskExecuteCommand (void)
Executes the command in the next_command struct.
void taskFetchCommand (void)
Task to fetch a new command.
void taskParseCommand ()
Sets the next_command struct members according to the buffered string.
uint8_t fetchCommand (uint8_t *dest)
Loads a command into a string if the format is correect.
Variables
command next_command
static uint8_t command_string [9]
Function Documentation
fetchCommand()
uint8_t fetchCommand (uint8_t * dest)
Loads a command into a string if the format is correect.
Returns
uint8_t 1 on success
Definition at line 54 of file commands.c.
Referenced by taskFetchCommand().
initCommands()
void initCommands (void)
Used only to initialize the command structs function pointer to NULL.
Definition at line 10 of file commands.c.
Referenced by main().
taskExecuteCommand()
void taskExecuteCommand (void)
Executes the command in the next_command struct.
Definition at line 15 of file commands.c.
Referenced by main().
taskFetchCommand()
void taskFetchCommand (void)
Task to fetch a new command.
Definition at line 26 of file commands.c.
Referenced by main().
taskParseCommand()
void taskParseCommand (void)
Sets the next_command struct members according to the buffered string.
Definition at line 32 of file commands.c.
Referenced by main().
Variable Documentation
command_string
uint8_t command_string[9] static
Definition at line 9 of file commands.c.
Referenced by taskFetchCommand(), and taskParseCommand().
next_command
command next_command
Definition at line 8 of file commands.c.
Referenced by initCommands(), taskExecuteCommand(), and taskParseCommand().