UART thermostat: include/commands.h File Reference
commands.h File Reference
#include <inttypes.h>
Data Structures
struct command
struct to store the next command func and arguments
Macros
#define COMMAND_BUFFER_LENGTH 3
Typedefs
typedef void(* CommandFunc) (uint8_t, uint8_t *)
typedef struct command command
struct to store the next command func and arguments
Functions
uint8_t fetchCommand (uint8_t *)
Loads a command into a string if the format is correect.
void taskFetchCommand (void)
Task to fetch a new command.
void initCommands (void)
Used only to initialize the command structs function pointer to NULL.
void taskExecuteCommand (void)
Executes the command in the next_command struct.
void taskParseCommand (void)
Sets the next_command struct members according to the buffered string.
Macro Definition Documentation
COMMAND_BUFFER_LENGTH
#define COMMAND_BUFFER_LENGTH 3
Definition at line 4 of file commands.h.
Typedef Documentation
command
typedef struct command command
struct to store the next command func and arguments
CommandFunc
typedef void(* CommandFunc) (uint8_t, uint8_t *)
Definition at line 39 of file commands.h.
Function Documentation
fetchCommand()
uint8_t fetchCommand (uint8_t * dest)
Loads a command into a string if the format is correect.
Returns
uint8_t 1 on success
Definition at line 54 of file commands.c.
Referenced by taskFetchCommand().
initCommands()
void initCommands (void)
Used only to initialize the command structs function pointer to NULL.
Definition at line 10 of file commands.c.
Referenced by main().
taskExecuteCommand()
void taskExecuteCommand (void)
Executes the command in the next_command struct.
Definition at line 15 of file commands.c.
Referenced by main().
taskFetchCommand()
void taskFetchCommand (void)
Task to fetch a new command.
Definition at line 26 of file commands.c.
Referenced by main().
taskParseCommand()
void taskParseCommand (void)
Sets the next_command struct members according to the buffered string.
Definition at line 32 of file commands.c.
Referenced by main().