UART thermostat: src/display_manager.c File Reference
display_manager.c File Reference
#include <avr/io.h>
#include "display_manager.h"
#include "room_manager.h"
#include "lcd.h"
#include <stdio.h>
#include "uart.h"
Functions
void initDisplayManager (void)
Initialize the display manager.
void setCurrentPage (uint8_t page)
Set the Current Page.
void taskPrintPage (void)
Print the page according to the current_page var.
static void printMainMenu (void)
static void printRoomPage ()
Variables
static uint8_t current_page = 2
Function Documentation
initDisplayManager()
void initDisplayManager (void)
Initialize the display manager.
Definition at line 10 of file display_manager.c.
Referenced by main().
printMainMenu()
static void printMainMenu (void) static
Definition at line 30 of file display_manager.c.
Referenced by printRoomPage().
printRoomPage()
static void printRoomPage () static
Definition at line 39 of file display_manager.c.
Referenced by taskPrintPage().
setCurrentPage()
void setCurrentPage (uint8_t page)
Set the Current Page.
Parameters
page
Definition at line 20 of file display_manager.c.
Referenced by taskButtonCheck().
taskPrintPage()
void taskPrintPage (void)
Print the page according to the current_page var.
Definition at line 25 of file display_manager.c.
Referenced by main().
Variable Documentation
current_page
uint8_t current_page = 2 static
Definition at line 8 of file display_manager.c.
Referenced by printRoomPage(), setCurrentPage(), and taskPrintPage().