UART thermostat: include/display_manager.h File Reference
display_manager.h File Reference
#include <inttypes.h>
Functions
void initDisplayManager (void)
Initialize the display manager.
void setCurrentPage (uint8_t page)
Set the Current Page.
void taskPrintPage (void)
Print the page according to the current_page var.
static void printMainMenu (void)
Print the main menu.
static void printRoomPage ()
Print a page and set status led accordingly.
Function Documentation
initDisplayManager()
void initDisplayManager (void)
Initialize the display manager.
Definition at line 10 of file display_manager.c.
Referenced by main().
printMainMenu()
static void printMainMenu (void) static
Print the main menu.
printRoomPage()
static void printRoomPage () static
Print a page and set status led accordingly.
Parameters
current_page number of the page to be printed 1-4
setCurrentPage()
void setCurrentPage (uint8_t page)
Set the Current Page.
Parameters
page
Definition at line 20 of file display_manager.c.
Referenced by taskButtonCheck().
taskPrintPage()
void taskPrintPage (void)
Print the page according to the current_page var.
Definition at line 25 of file display_manager.c.
Referenced by main().