UART thermostat: src/io_manager.c File Reference
io_manager.c File Reference
#include <avr/io.h>
#include "matrix.h"
#include "room_manager.h"
#include "display_manager.h"
#include "uart.h"
#include "io_manager.h"
Functions
void initIOManager (void)
Initialize the module.
void taskButtonCheck (void)
Task to check for a button press.
void taskManageActuators (void)
Task to control the actuators.
void initLEDS (void)
Initialize the LEDs.
Function Documentation
initIOManager()
void initIOManager (void)
Initialize the module.
Definition at line 8 of file io_manager.c.
Referenced by main().
initLEDS()
void initLEDS (void)
Initialize the LEDs.
Definition at line 60 of file io_manager.c.
Referenced by initIOManager().
taskButtonCheck()
void taskButtonCheck (void)
Task to check for a button press.
Definition at line 13 of file io_manager.c.
Referenced by main().
taskManageActuators()
void taskManageActuators (void)
Task to control the actuators.
Definition at line 36 of file io_manager.c.
Referenced by main().