UART thermostat: src/lcd.c File Reference
lcd.c File Reference
#include <util/delay.h>
#include <avr/io.h>
#include "lcd.h"
#include <avr/interrupt.h>
Macros
#define F_CPU 16000000UL
Functions
void initLCD (void)
Initialize the LCD.
void LCD_enable ()
Sends enable signal to the display.
void LCD_command (uint8_t cmd)
Send a command to the display.
void LCD_data (uint8_t data)
Send data to the display.
void LCD_str (uint8_t *t)
Write a string on the display.
void LCD_pos (uint8_t x, uint8_t y)
Sets the position of the cursor on the display.
void lcdPrintRows (uint8_t **row_array)
Prints multiple rows on the display.
Macro Definition Documentation
F_CPU
#define F_CPU 16000000UL
Definition at line 2 of file lcd.c.
Function Documentation
initLCD()
void initLCD (void)
Initialize the LCD.
Definition at line 8 of file lcd.c.
Referenced by initDisplayManager().
LCD_command()
void LCD_command (uint8_t cmd)
Send a command to the display.
Parameters
cmd code of the command
Definition at line 33 of file lcd.c.
Referenced by initLCD(), LCD_pos(), and lcdPrintRows().
LCD_data()
void LCD_data (uint8_t data)
Send data to the display.
Parameters
data to be sent
Definition at line 48 of file lcd.c.
Referenced by LCD_str().
LCD_enable()
void LCD_enable (void)
Sends enable signal to the display.
Definition at line 25 of file lcd.c.
Referenced by initLCD(), LCD_command(), and LCD_data().
LCD_pos()
void LCD_pos (uint8_t x, uint8_t y)
Sets the position of the cursor on the display.
Parameters
x
y
Definition at line 71 of file lcd.c.
Referenced by lcdPrintRows(), and printRoomPage().
LCD_str()
void LCD_str (uint8_t * t)
Write a string on the display.
Parameters
t
Definition at line 63 of file lcd.c.
Referenced by lcdPrintRows(), and printRoomPage().
lcdPrintRows()
void lcdPrintRows (uint8_t ** row_array)
Prints multiple rows on the display.
Definition at line 95 of file lcd.c.
Referenced by printMainMenu().