UART thermostat: include/lcd.h File Reference
lcd.h File Reference
#include <avr/io.h>
Macros
#define LCD_RS (PF1)
#define LCD_RW (PF2)
#define LCD_E (PF3)
#define LCD_CMD_DDR (DDRF)
#define LCD_DATA_DDR (DDRE)
#define LCD_CMD_PORT (PORTF)
#define LCD_DATA_PORT (PORTE)
Functions
void initLCD (void)
Initialize the LCD.
void LCD_command (uint8_t cmd)
Send a command to the display.
void LCD_data (uint8_t data)
Send data to the display.
void LCD_enable (void)
Sends enable signal to the display.
void LCD_str (uint8_t *t)
Write a string on the display.
void LCD_pos (uint8_t x, uint8_t y)
Sets the position of the cursor on the display.
void lcdPrintRows (uint8_t **)
Prints multiple rows on the display.
Macro Definition Documentation
LCD_CMD_DDR
#define LCD_CMD_DDR (DDRF)
Definition at line 15 of file lcd.h.
LCD_CMD_PORT
#define LCD_CMD_PORT (PORTF)
Definition at line 18 of file lcd.h.
LCD_DATA_DDR
#define LCD_DATA_DDR (DDRE)
Definition at line 16 of file lcd.h.
LCD_DATA_PORT
#define LCD_DATA_PORT (PORTE)
Definition at line 19 of file lcd.h.
LCD_E
#define LCD_E (PF3)
Definition at line 13 of file lcd.h.
LCD_RS
#define LCD_RS (PF1)
Definition at line 11 of file lcd.h.
LCD_RW
#define LCD_RW (PF2)
Definition at line 12 of file lcd.h.
Function Documentation
initLCD()
void initLCD (void)
Initialize the LCD.
Definition at line 8 of file lcd.c.
Referenced by initDisplayManager().
LCD_command()
void LCD_command (uint8_t cmd)
Send a command to the display.
Parameters
cmd code of the command
Definition at line 33 of file lcd.c.
Referenced by initLCD(), LCD_pos(), and lcdPrintRows().
LCD_data()
void LCD_data (uint8_t data)
Send data to the display.
Parameters
data to be sent
Definition at line 48 of file lcd.c.
Referenced by LCD_str().
LCD_enable()
void LCD_enable (void)
Sends enable signal to the display.
Definition at line 25 of file lcd.c.
Referenced by initLCD(), LCD_command(), and LCD_data().
LCD_pos()
void LCD_pos (uint8_t x, uint8_t y)
Sets the position of the cursor on the display.
Parameters
x
y
Definition at line 71 of file lcd.c.
Referenced by lcdPrintRows(), and printRoomPage().
LCD_str()
void LCD_str (uint8_t * t)
Write a string on the display.
Parameters
t
Definition at line 63 of file lcd.c.
Referenced by lcdPrintRows(), and printRoomPage().
lcdPrintRows()
void lcdPrintRows (uint8_t ** row_array)
Prints multiple rows on the display.
Definition at line 95 of file lcd.c.
Referenced by printMainMenu().