UART thermostat: include/lm35.h File Reference
lm35.h File Reference
#include "inttypes.h"
Functions
void initADC (void)
Initialize ADC peripheral.
void taskPollTemp (void)
Initiates a conversion and stores a value in integer and string format.
void log_adc_val (uint16_t)
Logs the adc value for debugging purposes.
void taskRegisterTemp ()
Converts the ADC value into temperature and stores it in string and integer format.
uint8_t * getTempString (void)
Get the Temp String.
uint16_t getCurrentTemp (void)
Get the Current Temp.
Function Documentation
getCurrentTemp()
uint16_t getCurrentTemp (void)
Get the Current Temp.
Returns
uint16_t
Definition at line 66 of file lm35.c.
Referenced by createRooms().
getTempString()
uint8_t * getTempString (void)
Get the Temp String.
Returns
uint8_t*
Definition at line 71 of file lm35.c.
initADC()
void initADC (void)
Initialize ADC peripheral.
Definition at line 13 of file lm35.c.
Referenced by main().
log_adc_val()
void log_adc_val (uint16_t val)
Logs the adc value for debugging purposes.
Parameters
val
Definition at line 34 of file lm35.c.
taskPollTemp()
void taskPollTemp (void)
Initiates a conversion and stores a value in integer and string format.
Definition at line 27 of file lm35.c.
Referenced by initADC(), and main().
taskRegisterTemp()
void taskRegisterTemp ()
Converts the ADC value into temperature and stores it in string and integer format.
Definition at line 42 of file lm35.c.
Referenced by initADC(), and main().