UART thermostat: src/lm35.c File Reference
lm35.c File Reference
#include "lm35.h"
#include "uart.h"
#include "inttypes.h"
#include "stdio.h"
#include "room_manager.h"
#include <avr/io.h>
Functions
void initADC ()
Initialize ADC peripheral.
void taskPollTemp ()
Initiates a conversion and stores a value in integer and string format.
void log_adc_val (uint16_t val)
Logs the adc value for debugging purposes.
void taskRegisterTemp ()
Converts the ADC value into temperature and stores it in string and integer format.
uint16_t getCurrentTemp ()
Get the Current Temp.
uint8_t * getTempString ()
Get the Temp String.
Variables
static uint16_t current_temp = 0
static uint16_t adcval = 0
static uint8_t * current_temp_string [5]
char debugstring [100]
Function Documentation
getCurrentTemp()
uint16_t getCurrentTemp (void)
Get the Current Temp.
Returns
uint16_t
Definition at line 66 of file lm35.c.
Referenced by createRooms().
getTempString()
uint8_t * getTempString (void)
Get the Temp String.
Returns
uint8_t*
Definition at line 71 of file lm35.c.
initADC()
void initADC (void)
Initialize ADC peripheral.
Definition at line 13 of file lm35.c.
Referenced by main().
log_adc_val()
void log_adc_val (uint16_t val)
Logs the adc value for debugging purposes.
Parameters
val
Definition at line 34 of file lm35.c.
taskPollTemp()
void taskPollTemp (void)
Initiates a conversion and stores a value in integer and string format.
Definition at line 27 of file lm35.c.
Referenced by initADC(), and main().
taskRegisterTemp()
void taskRegisterTemp ()
Converts the ADC value into temperature and stores it in string and integer format.
Definition at line 42 of file lm35.c.
Referenced by initADC(), and main().
Variable Documentation
adcval
uint16_t adcval = 0 static
Definition at line 8 of file lm35.c.
Referenced by taskPollTemp(), and taskRegisterTemp().
current_temp
uint16_t current_temp = 0 static
Definition at line 8 of file lm35.c.
Referenced by getCurrentTemp(), and taskRegisterTemp().
current_temp_string
uint8_t* current_temp_string[5] static
Definition at line 9 of file lm35.c.
Referenced by getTempString().
debugstring
char debugstring[100]
Definition at line 11 of file lm35.c.