UART thermostat: src/room_manager.c File Reference
room_manager.c File Reference
#include "room_manager.h"
#include <inttypes.h>
#include "lm35.h"
#include <stdlib.h>
Functions
void initRoomManager ()
Initializes the room manager.
static void createRooms ()
uint16_t getTargetRoomTemp (uint8_t room_no)
Get the target room temperature.
void setTargetRoomTemp (uint8_t room_no, uint8_t *target)
Set the target room temperature with a 3 digit value.
uint8_t getRoomCooling (uint8_t room_no)
Get the state of the room cooling.
void setRoomCooling (uint8_t room_no, uint8_t *state)
Enable or disable cooling.
uint16_t getRoomTemp (uint8_t room_no)
Get the Room Temp.
void setRoomTemp (uint8_t room_no, uint16_t temp)
Set the Room Temp.
Variables
static Room rooms [4]
static array to store rooms
Function Documentation
createRooms()
static void createRooms () static
Definition at line 19 of file room_manager.c.
Referenced by initRoomManager().
getRoomCooling()
uint8_t getRoomCooling (uint8_t room_no)
Get the state of the room cooling.
Parameters
room_no
Returns
uint8_t 1 or 0
Definition at line 58 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
getRoomTemp()
uint16_t getRoomTemp (uint8_t room_no)
Get the Room Temp.
Returns
uint16_t
Definition at line 69 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
getTargetRoomTemp()
uint16_t getTargetRoomTemp (uint8_t room_no)
Get the target room temperature.
Parameters
room_no
Returns
uint16_t The room temperature represented as a 3 digit value
Definition at line 47 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
initRoomManager()
void initRoomManager ()
Initializes the room manager.
Definition at line 14 of file room_manager.c.
Referenced by main().
setRoomCooling()
void setRoomCooling (uint8_t room_no, uint8_t * state)
Enable or disable cooling.
Parameters
room_no
state 1 or 0
Definition at line 63 of file room_manager.c.
Referenced by taskParseCommand().
setRoomTemp()
void setRoomTemp (uint8_t room_no, uint16_t temp)
Set the Room Temp.
Definition at line 74 of file room_manager.c.
Referenced by taskRegisterTemp().
setTargetRoomTemp()
void setTargetRoomTemp (uint8_t room_no, uint8_t * target)
Set the target room temperature with a 3 digit value.
Parameters
room_no
target the target temperature
Definition at line 52 of file room_manager.c.
Referenced by taskParseCommand().
Variable Documentation
rooms
Room rooms[4] static
static array to store rooms
Definition at line 12 of file room_manager.c.
Referenced by createRooms(), getRoomCooling(), getRoomTemp(), getTargetRoomTemp(), setRoomCooling(), setRoomTemp(), and setTargetRoomTemp().