UART thermostat: include/room_manager.h File Reference
room_manager.h File Reference
#include <inttypes.h>
Data Structures
struct Room
Macros
#define MAX_ROOMS_NO 4
Typedefs
typedef struct Room Room
Functions
void initRoomManager ()
Initializes the room manager.
static void createRooms ()
Create the rooms and stores it in an array.
uint16_t getTargetRoomTemp (uint8_t room_no)
Get the target room temperature.
void setTargetRoomTemp (uint8_t, uint8_t *)
Set the target room temperature with a 3 digit value.
uint8_t getRoomCooling (uint8_t)
Get the state of the room cooling.
void setRoomCooling (uint8_t, uint8_t *)
Enable or disable cooling.
uint16_t getRoomTemp (uint8_t)
Get the Room Temp.
void setRoomTemp (uint8_t, uint16_t)
Set the Room Temp.
Macro Definition Documentation
MAX_ROOMS_NO
#define MAX_ROOMS_NO 4
Definition at line 5 of file room_manager.h.
Typedef Documentation
Room
typedef struct Room Room
Function Documentation
createRooms()
static void createRooms () static
Create the rooms and stores it in an array.
getRoomCooling()
uint8_t getRoomCooling (uint8_t room_no)
Get the state of the room cooling.
Parameters
room_no
Returns
uint8_t 1 or 0
Definition at line 58 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
getRoomTemp()
uint16_t getRoomTemp (uint8_t room_no)
Get the Room Temp.
Returns
uint16_t
Definition at line 69 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
getTargetRoomTemp()
uint16_t getTargetRoomTemp (uint8_t room_no)
Get the target room temperature.
Parameters
room_no
Returns
uint16_t The room temperature represented as a 3 digit value
Definition at line 47 of file room_manager.c.
Referenced by printRoomPage(), and taskManageActuators().
initRoomManager()
void initRoomManager ()
Initializes the room manager.
Definition at line 14 of file room_manager.c.
Referenced by main().
setRoomCooling()
void setRoomCooling (uint8_t room_no, uint8_t * state)
Enable or disable cooling.
Parameters
room_no
state 1 or 0
Definition at line 63 of file room_manager.c.
Referenced by taskParseCommand().
setRoomTemp()
void setRoomTemp (uint8_t room_no, uint16_t temp)
Set the Room Temp.
Definition at line 74 of file room_manager.c.
Referenced by taskRegisterTemp().
setTargetRoomTemp()
void setTargetRoomTemp (uint8_t room_no, uint8_t * target)
Set the target room temperature with a 3 digit value.
Parameters
room_no
target the target temperature
Definition at line 52 of file room_manager.c.
Referenced by taskParseCommand().