UART thermostat: src/scheduler.c File Reference
scheduler.c File Reference
#include <avr/io.h>
#include <inttypes.h>
#include "scheduler.h"
#include "timer.h"
Functions
void tickTasks (void)
Decreases the delay of tasks at every tick.
void initScheduler (void)
Initializes the tasks in task_list and sets up timer.
void addTask (uint8_t id, task_t task, uint16_t period)
Add a new task at the first empty place.
void deleteTask (uint8_t id)
Remove a task from tasklist by ID. stopped=ignore.
uint8_t getTaskStatus (uint8_t id)
Get the status of a task.
void dispatchTasks (void)
Dispatch a task when it is ready.
Variables
tcb_t task_list [MAX_TASKS]
Function Documentation
addTask()
void addTask (uint8_t id, task_t task, uint16_t period)
Add a new task at the first empty place.
Parameters
id
task
period
Definition at line 30 of file scheduler.c.
Referenced by main().
deleteTask()
void deleteTask (uint8_t id)
Remove a task from tasklist by ID. stopped=ignore.
Parameters
id
Definition at line 51 of file scheduler.c.
dispatchTasks()
void dispatchTasks (void)
Dispatch a task when it is ready.
Definition at line 73 of file scheduler.c.
Referenced by main().
getTaskStatus()
uint8_t getTaskStatus (uint8_t id)
Get the status of a task.
Parameters
id
Returns
uint8_t
Definition at line 63 of file scheduler.c.
initScheduler()
void initScheduler (void)
Initializes the tasks in task_list and sets up timer.
Definition at line 17 of file scheduler.c.
Referenced by main().
tickTasks()
void tickTasks (void)
Decreases the delay of tasks at every tick.
Definition at line 8 of file scheduler.c.
Referenced by ISR().
Variable Documentation
task_list
tcb_t task_list[MAX_TASKS]
Definition at line 6 of file scheduler.c.
Referenced by addTask(), deleteTask(), dispatchTasks(), getTaskStatus(), initScheduler(), and tickTasks().