UART thermostat: include/scheduler.h File Reference
scheduler.h File Reference
#include <inttypes.h>
Data Structures
struct _tcb_t
Task struct.
Macros
#define READY (0x00)
#define RUNNING (0x01)
#define STOPPED (0x02)
#define ERROR (0x03)
#define MAX_TASKS (10)
#define INTERVAL_POLL_TEMP_100MS 600
#define INTERVAL_PRINT_PAGE_100MS 1
#define INTERVAL_BUTTON_CHECK_100MS 1
#define INTERVAL_MANAGE_ACTUATORS_100MS 50
#define INTERVAL_REGISTER_TEMP_100MS 100
#define INTERVAL_FETCH_COMMAND 30
#define INTERVAL_PARSE_COMMAND 20
#define INTERVAL_EXECUTE_COMMAND 10
Typedefs
typedef void(* task_t) (void)
points to a task function
typedef struct _tcb_t tcb_t
Task struct.
Functions
void initScheduler (void)
Initializes the tasks in task_list and sets up timer.
void addTask (uint8_t, task_t, uint16_t)
Add a new task at the first empty place.
void deleteTask (uint8_t)
Remove a task from tasklist by ID. stopped=ignore.
uint8_t getTaskStatus (uint8_t)
Get the status of a task.
void dispatchTasks (void)
Dispatch a task when it is ready.
void tickTasks (void)
Decreases the delay of tasks at every tick.
Macro Definition Documentation
ERROR
#define ERROR (0x03)
Definition at line 8 of file scheduler.h.
INTERVAL_BUTTON_CHECK_100MS
#define INTERVAL_BUTTON_CHECK_100MS 1
Definition at line 14 of file scheduler.h.
INTERVAL_EXECUTE_COMMAND
#define INTERVAL_EXECUTE_COMMAND 10
Definition at line 19 of file scheduler.h.
INTERVAL_FETCH_COMMAND
#define INTERVAL_FETCH_COMMAND 30
Definition at line 17 of file scheduler.h.
INTERVAL_MANAGE_ACTUATORS_100MS
#define INTERVAL_MANAGE_ACTUATORS_100MS 50
Definition at line 15 of file scheduler.h.
INTERVAL_PARSE_COMMAND
#define INTERVAL_PARSE_COMMAND 20
Definition at line 18 of file scheduler.h.
INTERVAL_POLL_TEMP_100MS
#define INTERVAL_POLL_TEMP_100MS 600
Definition at line 12 of file scheduler.h.
INTERVAL_PRINT_PAGE_100MS
#define INTERVAL_PRINT_PAGE_100MS 1
Definition at line 13 of file scheduler.h.
INTERVAL_REGISTER_TEMP_100MS
#define INTERVAL_REGISTER_TEMP_100MS 100
Definition at line 16 of file scheduler.h.
MAX_TASKS
#define MAX_TASKS (10)
Definition at line 9 of file scheduler.h.
READY
#define READY (0x00)
Definition at line 5 of file scheduler.h.
RUNNING
#define RUNNING (0x01)
Definition at line 6 of file scheduler.h.
STOPPED
#define STOPPED (0x02)
Definition at line 7 of file scheduler.h.
Typedef Documentation
task_t
typedef void(* task_t) (void)
points to a task function
Definition at line 25 of file scheduler.h.
tcb_t
typedef struct _tcb_t tcb_t
Task struct.
Function Documentation
addTask()
void addTask (uint8_t id, task_t task, uint16_t period)
Add a new task at the first empty place.
Parameters
id
task
period
Definition at line 30 of file scheduler.c.
Referenced by main().
deleteTask()
void deleteTask (uint8_t id)
Remove a task from tasklist by ID. stopped=ignore.
Parameters
id
Definition at line 51 of file scheduler.c.
dispatchTasks()
void dispatchTasks (void)
Dispatch a task when it is ready.
Definition at line 73 of file scheduler.c.
Referenced by main().
getTaskStatus()
uint8_t getTaskStatus (uint8_t id)
Get the status of a task.
Parameters
id
Returns
uint8_t
Definition at line 63 of file scheduler.c.
initScheduler()
void initScheduler (void)
Initializes the tasks in task_list and sets up timer.
Definition at line 17 of file scheduler.c.
Referenced by main().
tickTasks()
void tickTasks (void)
Decreases the delay of tasks at every tick.
Definition at line 8 of file scheduler.c.
Referenced by ISR().