UART thermostat: src/uart.c File Reference
uart.c File Reference
#include "uart.h"
#include "avr/io.h"
#include <inttypes.h>
#include <stdio.h>
Macros
#define F_CPU 16000000UL
Functions
void initUART (uint8_t ubrr)
Initialize UART interface.
void uartTransmitChar (uint8_t cp)
Transmits a character via UART.
void uartTransmitStr (uint8_t *str)
Trnsmits a string via UART.
void check_uart_error ()
Checks the UART error registers.
static uint8_t _buffer_is_full ()
static uint8_t _buffer_is_empty ()
void write_buffer (uint8_t data)
Writes a character to the buffer if there is space.
uint8_t read_buffer (uint8_t *dest)
read buffer into destination
Variables
uart_buffer rx_buffer
Macro Definition Documentation
F_CPU
#define F_CPU 16000000UL
Definition at line 1 of file uart.c.
Function Documentation
_buffer_is_empty()
static uint8_t _buffer_is_empty (void) static
Definition at line 63 of file uart.c.
Referenced by read_buffer().
_buffer_is_full()
static uint8_t _buffer_is_full (void) static
Definition at line 56 of file uart.c.
Referenced by write_buffer().
check_uart_error()
void check_uart_error (void)
Checks the UART error registers.
Definition at line 46 of file uart.c.
Referenced by ISR().
initUART()
void initUART (uint8_t ubrr)
Initialize UART interface.
Parameters
ubrr
Definition at line 9 of file uart.c.
Referenced by main().
read_buffer()
uint8_t read_buffer (uint8_t * dest)
read buffer into destination
Parameters
dest
Returns
uint8_t 1 on successful read, 0 on empty
Definition at line 90 of file uart.c.
Referenced by fetchCommand().
uartTransmitChar()
void uartTransmitChar (uint8_t cp)
Transmits a character via UART.
Parameters
cp
Definition at line 26 of file uart.c.
Referenced by uartTransmitStr().
uartTransmitStr()
void uartTransmitStr (uint8_t * str)
Trnsmits a string via UART.
Parameters
str
Definition at line 33 of file uart.c.
Referenced by check_uart_error(), log_adc_val(), and write_buffer().
write_buffer()
void write_buffer (uint8_t data)
Writes a character to the buffer if there is space.
Parameters
data
Definition at line 70 of file uart.c.
Referenced by ISR().
Variable Documentation
rx_buffer
uart_buffer rx_buffer
Definition at line 7 of file uart.c.
Referenced by _buffer_is_empty(), _buffer_is_full(), initUART(), read_buffer(), and write_buffer().