UART thermostat: include/uart.h File Reference
uart.h File Reference
#include <inttypes.h>
Data Structures
struct uart_buffer
Macros
#define BAUD_RATE 115200
#define UBRR ((F_CPU / 8 / BAUD_RATE) - 1)
#define UART_BUFFER_SIZE 60
Typedefs
typedef struct uart_buffer uart_buffer
Functions
void initUART (uint8_t)
Initialize UART interface.
void uartTransmitChar (uint8_t)
Transmits a character via UART.
void uartReceive (void)
void uartTransmitStr (uint8_t *)
Trnsmits a string via UART.
void check_uart_error (void)
Checks the UART error registers.
uint8_t read_buffer (uint8_t *)
read buffer into destination
static uint8_t _buffer_is_full (void)
check if the buffer is full
static uint8_t _buffer_is_empty (void)
check if buffer is empty
void write_buffer (uint8_t data)
Writes a character to the buffer if there is space.
Macro Definition Documentation
BAUD_RATE
#define BAUD_RATE 115200
Definition at line 6 of file uart.h.
UART_BUFFER_SIZE
#define UART_BUFFER_SIZE 60
Definition at line 8 of file uart.h.
UBRR
#define UBRR ((F_CPU / 8 / BAUD_RATE) - 1)
Definition at line 7 of file uart.h.
Typedef Documentation
uart_buffer
typedef struct uart_buffer uart_buffer
Function Documentation
_buffer_is_empty()
static uint8_t _buffer_is_empty (void) static
check if buffer is empty
Returns
uint8_t 1 if empty 0 if not
_buffer_is_full()
static uint8_t _buffer_is_full (void) static
check if the buffer is full
Returns
uint8_t 1 if true
check_uart_error()
void check_uart_error (void)
Checks the UART error registers.
Definition at line 46 of file uart.c.
Referenced by ISR().
initUART()
void initUART (uint8_t ubrr)
Initialize UART interface.
Parameters
ubrr
Definition at line 9 of file uart.c.
Referenced by main().
read_buffer()
uint8_t read_buffer (uint8_t * dest)
read buffer into destination
Parameters
dest
Returns
uint8_t 1 on successful read, 0 on empty
Definition at line 90 of file uart.c.
Referenced by fetchCommand().
uartReceive()
void uartReceive (void)
uartTransmitChar()
void uartTransmitChar (uint8_t cp)
Transmits a character via UART.
Parameters
cp
Definition at line 26 of file uart.c.
Referenced by uartTransmitStr().
uartTransmitStr()
void uartTransmitStr (uint8_t * str)
Trnsmits a string via UART.
Parameters
str
Definition at line 33 of file uart.c.
Referenced by check_uart_error(), log_adc_val(), and write_buffer().
write_buffer()
void write_buffer (uint8_t data)
Writes a character to the buffer if there is space.
Parameters
data
Definition at line 70 of file uart.c.
Referenced by ISR().